version: '2.2'

  mysql:
    restart: unless-stopped
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: mysqlrootpassword
      MYSQL_DATABASE: mautic
      MYSQL_USER: mautic
      MYSQL_PASSWORD: mauticdbpass
    volumes:
      - mysql-data:/var/lib/mysql

  mautic:
    depends_on:
      - mysql    
    image: ivanmonteiro/docker-mautic-lightweight:latest
    restart: unless-stopped
    environment:
      MAUTIC_DB_HOST: mysql
      MAUTIC_DB_USER: mautic
      MAUTIC_DB_PASSWORD: mauticdbpass
      MAUTIC_DB_NAME: mautic
      MAUTIC_RUN_CRON_JOBS: true
      PHP_MEMORY_LIMIT: 128M
    volumes:
      - ./php-fpm/www2-override-mautic-fpm.conf:/usr/local/etc/php-fpm.d/www2-override.conf
      - ./public/:/var/www/html/      
    # cpus: '0.5' # uncomment if you run multiple applications mautic is using too much cpu on your server

  nginx:
    depends_on:
      - mautic
    image: nginx:latest
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./public/:/var/www/html/
      - ./nginx/mautic-fpm-nginx.conf:/etc/nginx/conf.d/mautic-fpm-nginx.conf

volumes:
  mysql-data:
